export const crudConstants = {
    ADD_PAGE:"ADD_PAGE",
    DELETE_PAGE:"DELETE_PAGE",
    FETCH_PAGE:"FETCH_PAGE",
    UPDATE_PAGE:"UPDATE_PAGE",
    ADD_TEXT:"ADD_TEXT",
    DELETE_TEXT:"DELETE_TEXT",
    FETCH_TEXT:"FETCH_TEXT",
    UPDATE_TEXT:"UPDATE_TEXT",
    ADD_LANGUE:"ADD_LANGUE",
    DELETE_LANGUE:"DELETE_LANGUE",
    FETCH_LANGUE:"FETCH_LANGUE",
    UPDATE_LANGUE:"UPDATE_LANGUE"
};
